spring:
  profiles:
    active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: false
  rabbitmq:
    host: 192.168.99.100
    port: 5672    
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7000
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
server:
  port: 7000	  
---
spring:
  profiles: cloud
  datasource:
    url: jdbc:mysql://mysql.openshift-infra:3306/mysqldb?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 10
    maxIdle: 5
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
    username: admin
    password: admin
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://user-service/uaa/user
    client:
      client-id: acme    
      access-token-uri: http://order-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service-peer1/eureka/,http://discovery-service-peer2/eureka/
server:
  port: 8080
logging:
  config: classpath:log-cloud.xml  
---
spring:
  application:
    name: account-service
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
server:
  port: 7000