spring:
  profiles:
    active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672    	
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#graphite.host: 192.168.99.100
#graphite.port: 2003
server:
  port: 7001
logging:
  config: log-cloud.xml
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
server:
  port: 7001
---
spring:
  profiles: cloud
  datasource:
    url: jdbc:mysql://mysql.openshift-infra:3306/mysqldb?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 10
    maxIdle: 5
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
    username: admin
    password: admin
    initialize: true
# rabbitmq:
#   host: 192.168.99.100
#   port: 5672    	
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service-peer1/eureka/,http://discovery-service-peer2/eureka/
server:
  port: 8080
logging:
  config: classpath:log-cloud.xml  
---
spring:
  profiles: test
  jpa:
    database: H2
  datasource:
    initialize: false
server:
  port: 7001