spring:
  profiles:
    active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672    	
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#graphite.host: 192.168.99.100
#graphite.port: 2003
server:
  port: 7001
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
server:
  port: 7001
---
spring:
  profiles: cloud
  datasource:
#    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    url: jdbc:mysql://mysql.openshift-infra:3306/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: true
# rabbitmq:
#   host: 192.168.99.100
#   port: 5672    	
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service-peer1/eureka/,http://discovery-service-peer2/eureka/
#http://${DISCOVERY_SERVICE_PEER1_SERVICE_HOST}:${DISCOVERY_SERVICE_PEER1_SERVICE_PORT}/eureka/,http://${DISCOVERY_SERVICE_PEER2_SERVICE_HOST}:${DISCOVERY_SERVICE_PEER2_SERVICE_PORT}/eureka/
server:
  port: 8080
---
spring:
  profiles: test
  jpa:
    database: H2
  datasource:
    initialize: false
server:
  port: 7001