spring:
  profiles:
    active: development
server:
  port: 8761
---
spring:
  profiles: development
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: peer1
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_PEER2_SERVICE_HOST}:${DISCOVERY_SERVICE_PEER2_SERVICE_PORT}/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: peer2
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_PEER1_SERVICE_HOST}:${DISCOVERY_SERVICE_PEER1_SERVICE_HOST}/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0