spring:
  profiles:
    active: development
---
spring:
  profiles: development
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0
server:
  port: 8761
---
spring:
  profiles: peer1
eureka:
  instance:
    prefer-ip-address: true
#leaseRenewalIntervalSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service-peer2/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0
server:
  port: 8080
---
spring:
  profiles: peer2
eureka:
  instance:
    prefer-ip-address: true
#leaseRenewalIntervalSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service-peer1/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0
server:
  port: 8080