spring:
  profiles:
    active: development
---
spring:
  profiles: development
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: peer1
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_REPLICA_SERVICE_HOST}:${DISCOVERY_SERVICE_REPLICA_SERVICE_PORT}/eureka/
  instance:
    leaseRenewalIntervalSeconds: 10
  server:
      waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: peer2
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_SERVICE_HOST}:${DISCOVERY_SERVICE_SERVICE_PORT}/eureka/